GET http://localhost:8085/api/users/me/history
Authorization: Bearer 9b08583a-4374-46e3-9017-19c18b347d3b

###

### יצירת מירוץ חדש
POST http://localhost:8085/api/race/create
Content-Type: application/json
Authorization: Bearer fd8e192a-d3fb-40e5-b312-2849890bff63

{
  "name": "חדש כרגע",
  "targetScore": 500,
  "nickname": "ShimonTheKing"
}

###

POST http://localhost:8085/api/auth/register
Content-Type: application/json

{
  "username" : "ere",
  "email": "1@gmail.com",
  "password" :  "eoivnekdfj "
}

###

DELETE http://localhost:8085/api/users/me?token=dssfsd
Authorization: Bearer b7e463b2-f2ea-4420-999d-2fdf1daa9d47
