spring.application.name=math-race
server.port=8085

spring.web.resources.add-mappings=false
spring.mvc.throw-exception-if-no-handler-found=true

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.mail.default-encoding=UTF-8


spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=mathaceservice@gmail.com
spring.mail.password=ilcmlelmupgvubaa

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


spring.task.execution.pool.core-size=5
spring.task.execution.pool.max-size=10
spring.task.execution.pool.queue-capacity=100